

map_dic={}
map_dic['0'] = '0'
map_dic['1'] = 'A'
map_dic['2'] = '2'
map_dic['3'] = '3'
map_dic['4'] = '4'
map_dic['5'] = '5'
map_dic['6'] = '6'
map_dic['7'] = '7'
map_dic['8'] = '8'
map_dic['9'] = '9'
map_dic['10'] = 'B'
map_dic['11'] = 'C'
map_dic['12'] = 'D'
map_dic['13'] = 'E'
map_dic['14'] = 'F'
map_dic['15'] = 'G'
map_dic['16'] = 'H'
map_dic['17'] = 'I'
map_dic['18'] = 'J'
map_dic['19'] = 'K'
map_dic['20'] = 'L'
map_dic['21'] = 'M'
map_dic['22'] = 'N'
map_dic['23'] = 'P'
map_dic['24'] = 'Q'
map_dic['25'] = 'R'
map_dic['26'] = 'S'
map_dic['27'] = 'T'
map_dic['28'] = 'U'
map_dic['29'] = 'V'
map_dic['30'] = 'W'
map_dic['31'] = 'X'
map_dic['32'] = 'Y'
map_dic['33'] = 'Z'

